export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const LOG_OUT = "LOG_OUT";
export const GET_ALLUSERS = "GET_ALLUSERS";
export const DELETEUSER = "DELETEUSER";
export const BLOCKUSER = "BLOCKUSER";
// actionTypes recipe

export const ADDRECIPE = "ADDRECIPE";
export const ADDRECIPE_SUCCESS = "ADDRECIPE_SUCCESS";
export const ADDRECIPE_FAIL = "ADDRECIPE_FAIL";

export const GETRECIPES = "GETRECIPES";

export const UPDATERECIPE = "UPDATERECIPE";
export const DELETERECIPE = "DELETERECIPE";

export const DETAILRECIPE = "DETAILRECIPE";
export const DETAILRECIPE_SUCCESS = "DETAILRECIPE_SUCCESS";
export const DETAILRECIPE_FAIL = "DETAILRECIPE_FAIL";

export const GET_FRENCH_RECIPES = "GET_FRENCH_RECIPES";
export const GET_AMERICAN_RECIPES = "GET_AMERICAN_RECIPES";
export const GET_ITALIAN_RECIPES = "GET_ITALIAN_RECIPES";
export const GET_INDIAN_RECIPES = "GET_INDIAN_RECIPES";
export const GET_MEXICAN_RECIPES = "GET_MEXICAN_RECIPES";
export const GET_KID_FRIENDLY_RECIPES = "GET_KID_FRIENDLY_RECIPES";
export const GET_TUNISIAN_RECIPES = "GET_TUNSIAN_RECIPES";

export const FAVORITE_ADD_ITEM = "FAVORITE_ADD_ITEM";
export const FAVORITE_ADD_ITEM_SUCCESS = "FAVORITE_ADD_ITEM_SUCCESS";
export const FAVORITE_ADD_ITEM_FAIL = "FAVORITE_ADD_ITEM_FAIL";

export const GETFAVORITEITEM = "GETFAVORITEITEM";

export const FAVORITE_REMOVE_ITEM = "FAVORITE_REMOVE_ITEM";
